// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AbstractAccountFactory$Type } from "./AbstractAccountFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AbstractAccountFactory"]: AbstractAccountFactory$Type;
    ["contracts/AbstractAccountFactory.sol:AbstractAccountFactory"]: AbstractAccountFactory$Type;
  }

  interface ContractTypesMap {
    ["AbstractAccountFactory"]: GetContractReturnType<AbstractAccountFactory$Type["abi"]>;
    ["contracts/AbstractAccountFactory.sol:AbstractAccountFactory"]: GetContractReturnType<AbstractAccountFactory$Type["abi"]>;
  }
}
