// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TransientSlot$Type } from "./TransientSlot";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TransientSlot"]: TransientSlot$Type;
    ["@openzeppelin/contracts/utils/TransientSlot.sol:TransientSlot"]: TransientSlot$Type;
  }

  interface ContractTypesMap {
    ["TransientSlot"]: GetContractReturnType<TransientSlot$Type["abi"]>;
    ["@openzeppelin/contracts/utils/TransientSlot.sol:TransientSlot"]: GetContractReturnType<TransientSlot$Type["abi"]>;
  }
}
