// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface TransientSlot$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "TransientSlot",
  "sourceName": "@openzeppelin/contracts/utils/TransientSlot.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220ac3151ebaca275fe197a9f8c49a68cedf3478edb7608da7c030b795fb604e0b164736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220ac3151ebaca275fe197a9f8c49a68cedf3478edb7608da7c030b795fb604e0b164736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "TransientSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TransientSlot$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/TransientSlot.sol:TransientSlot",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TransientSlot$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "TransientSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TransientSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/TransientSlot.sol:TransientSlot",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TransientSlot$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "TransientSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TransientSlot$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/TransientSlot.sol:TransientSlot",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TransientSlot$Type["abi"]>>;
}
