// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Math$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Math",
  "sourceName": "@openzeppelin/contracts/utils/math/Math.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220fe4e02625737cdc6e5df7a89e49f6326eee89d2e7f600f66a448560a69f761dc64736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220fe4e02625737cdc6e5df7a89e49f6326eee89d2e7f600f66a448560a69f761dc64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Math",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Math$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/math/Math.sol:Math",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Math$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Math",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Math$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/math/Math.sol:Math",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Math$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Math",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Math$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/math/Math.sol:Math",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Math$Type["abi"]>>;
}
