// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CustomSmartAccountFactory$Type } from "./CustomSmartAccountFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CustomSmartAccountFactory"]: CustomSmartAccountFactory$Type;
    ["contracts/CustomSmartAccountFactory.sol:CustomSmartAccountFactory"]: CustomSmartAccountFactory$Type;
  }

  interface ContractTypesMap {
    ["CustomSmartAccountFactory"]: GetContractReturnType<CustomSmartAccountFactory$Type["abi"]>;
    ["contracts/CustomSmartAccountFactory.sol:CustomSmartAccountFactory"]: GetContractReturnType<CustomSmartAccountFactory$Type["abi"]>;
  }
}
