// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IStakeManager$Type } from "./IStakeManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IStakeManager"]: IStakeManager$Type;
    ["contracts/interfaces/IStakeManager.sol:IStakeManager"]: IStakeManager$Type;
  }

  interface ContractTypesMap {
    ["IStakeManager"]: GetContractReturnType<IStakeManager$Type["abi"]>;
    ["contracts/interfaces/IStakeManager.sol:IStakeManager"]: GetContractReturnType<IStakeManager$Type["abi"]>;
  }
}
