// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Eip7702Support$Type } from "./Eip7702Support";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Eip7702Support"]: Eip7702Support$Type;
    ["contracts/Eip7702Support.sol:Eip7702Support"]: Eip7702Support$Type;
  }

  interface ContractTypesMap {
    ["Eip7702Support"]: GetContractReturnType<Eip7702Support$Type["abi"]>;
    ["contracts/Eip7702Support.sol:Eip7702Support"]: GetContractReturnType<Eip7702Support$Type["abi"]>;
  }
}
