// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Eip7702Support$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Eip7702Support",
  "sourceName": "contracts/Eip7702Support.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208c9033bf3d652ee6543ecc2d378e95a27057db46834b9fe54ca32d916371718f64736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208c9033bf3d652ee6543ecc2d378e95a27057db46834b9fe54ca32d916371718f64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Eip7702Support",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Eip7702Support$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/Eip7702Support.sol:Eip7702Support",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Eip7702Support$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Eip7702Support",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Eip7702Support$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/Eip7702Support.sol:Eip7702Support",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Eip7702Support$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Eip7702Support",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Eip7702Support$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/Eip7702Support.sol:Eip7702Support",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Eip7702Support$Type["abi"]>>;
}
