// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Panic$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Panic",
  "sourceName": "@openzeppelin/contracts/utils/Panic.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220cca8e34ba4a10a3072e457ee409c3e14973552ffad66786674cea596605f229764736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220cca8e34ba4a10a3072e457ee409c3e14973552ffad66786674cea596605f229764736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Panic$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Panic.sol:Panic",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Panic$Type["abi"]>>;
}
