// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignedMath$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SignedMath",
  "sourceName": "@openzeppelin/contracts/utils/math/SignedMath.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208a55ed03b5bd2a413c0af052249d29c7f889c11b46b32ff454a480fb14df671c64736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212208a55ed03b5bd2a413c0af052249d29c7f889c11b46b32ff454a480fb14df671c64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignedMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/math/SignedMath.sol:SignedMath",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignedMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignedMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/math/SignedMath.sol:SignedMath",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignedMath$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignedMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/math/SignedMath.sol:SignedMath",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignedMath$Type["abi"]>>;
}
