// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ISenderCreator$Type } from "./ISenderCreator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISenderCreator"]: ISenderCreator$Type;
    ["contracts/interfaces/ISenderCreator.sol:ISenderCreator"]: ISenderCreator$Type;
  }

  interface ContractTypesMap {
    ["ISenderCreator"]: GetContractReturnType<ISenderCreator$Type["abi"]>;
    ["contracts/interfaces/ISenderCreator.sol:ISenderCreator"]: GetContractReturnType<ISenderCreator$Type["abi"]>;
  }
}
