// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISenderCreator$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ISenderCreator",
  "sourceName": "contracts/interfaces/ISenderCreator.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "initCode",
          "type": "bytes"
        }
      ],
      "name": "createSender",
      "outputs": [
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "internalType": "bytes",
          "name": "initCallData",
          "type": "bytes"
        }
      ],
      "name": "initEip7702Sender",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISenderCreator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISenderCreator$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/interfaces/ISenderCreator.sol:ISenderCreator",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISenderCreator$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISenderCreator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISenderCreator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/interfaces/ISenderCreator.sol:ISenderCreator",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISenderCreator$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISenderCreator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISenderCreator$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/interfaces/ISenderCreator.sol:ISenderCreator",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISenderCreator$Type["abi"]>>;
}
