// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Ownable2Step$Type } from "./Ownable2Step";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Ownable2Step"]: Ownable2Step$Type;
    ["@openzeppelin/contracts/access/Ownable2Step.sol:Ownable2Step"]: Ownable2Step$Type;
  }

  interface ContractTypesMap {
    ["Ownable2Step"]: GetContractReturnType<Ownable2Step$Type["abi"]>;
    ["@openzeppelin/contracts/access/Ownable2Step.sol:Ownable2Step"]: GetContractReturnType<Ownable2Step$Type["abi"]>;
  }
}
