// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AbstractAccount$Type } from "./AbstractAccount";
import { IEntryPoint$Type } from "./IEntryPoint";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AbstractAccount"]: AbstractAccount$Type;
    ["IEntryPoint"]: IEntryPoint$Type;
    ["contracts/AbstractAccount.sol:AbstractAccount"]: AbstractAccount$Type;
    ["contracts/AbstractAccount.sol:IEntryPoint"]: IEntryPoint$Type;
  }

  interface ContractTypesMap {
    ["AbstractAccount"]: GetContractReturnType<AbstractAccount$Type["abi"]>;
    ["IEntryPoint"]: GetContractReturnType<IEntryPoint$Type["abi"]>;
    ["contracts/AbstractAccount.sol:AbstractAccount"]: GetContractReturnType<AbstractAccount$Type["abi"]>;
    ["contracts/AbstractAccount.sol:IEntryPoint"]: GetContractReturnType<IEntryPoint$Type["abi"]>;
  }
}
