// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CustomSmartAccount$Type } from "./CustomSmartAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CustomSmartAccount"]: CustomSmartAccount$Type;
    ["contracts/CustomSmartAccount.sol:CustomSmartAccount"]: CustomSmartAccount$Type;
  }

  interface ContractTypesMap {
    ["CustomSmartAccount"]: GetContractReturnType<CustomSmartAccount$Type["abi"]>;
    ["contracts/CustomSmartAccount.sol:CustomSmartAccount"]: GetContractReturnType<CustomSmartAccount$Type["abi"]>;
  }
}
