// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Exec$Type } from "./Exec";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Exec"]: Exec$Type;
    ["contracts/utils/Exec.sol:Exec"]: Exec$Type;
  }

  interface ContractTypesMap {
    ["Exec"]: GetContractReturnType<Exec$Type["abi"]>;
    ["contracts/utils/Exec.sol:Exec"]: GetContractReturnType<Exec$Type["abi"]>;
  }
}
