// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Exec$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Exec",
  "sourceName": "contracts/utils/Exec.sol",
  "abi": [],
  "bytecode": "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220027326420c11dc99f11b28324113f590e4d8375f57243b96e58e5c6d24119c0a64736f6c634300081c0033",
  "deployedBytecode": "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220027326420c11dc99f11b28324113f590e4d8375f57243b96e58e5c6d24119c0a64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Exec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/utils/Exec.sol:Exec",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Exec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Exec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/utils/Exec.sol:Exec",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Exec$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Exec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/utils/Exec.sol:Exec",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Exec$Type["abi"]>>;
}
