// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { UserOperationLib$Type } from "./UserOperationLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UserOperationLib"]: UserOperationLib$Type;
    ["contracts/UserOperationLib.sol:UserOperationLib"]: UserOperationLib$Type;
  }

  interface ContractTypesMap {
    ["UserOperationLib"]: GetContractReturnType<UserOperationLib$Type["abi"]>;
    ["contracts/UserOperationLib.sol:UserOperationLib"]: GetContractReturnType<UserOperationLib$Type["abi"]>;
  }
}
