// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface UserOperationLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "UserOperationLib",
  "sourceName": "contracts/UserOperationLib.sol",
  "abi": [
    {
      "inputs": [],
      "name": "PAYMASTER_DATA_OFFSET",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "PAYMASTER_POSTOP_GAS_OFFSET",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "PAYMASTER_VALIDATION_GAS_OFFSET",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x60a76032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106046575f3560e01c806325093e1b14604a578063b29a8ff4146063578063ede3150214606a575b5f5ffd5b6051602481565b60405190815260200160405180910390f35b6051601481565b605160348156fea26469706673582212204cc52df6d7c0158292c9e688d1e0589f230aeddc29bb877e196dc66dc42e2ffb64736f6c634300081c0033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600436106046575f3560e01c806325093e1b14604a578063b29a8ff4146063578063ede3150214606a575b5f5ffd5b6051602481565b60405190815260200160405180910390f35b6051601481565b605160348156fea26469706673582212204cc52df6d7c0158292c9e688d1e0589f230aeddc29bb877e196dc66dc42e2ffb64736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "UserOperationLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/UserOperationLib.sol:UserOperationLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "UserOperationLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UserOperationLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/UserOperationLib.sol:UserOperationLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<UserOperationLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "UserOperationLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/UserOperationLib.sol:UserOperationLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<UserOperationLib$Type["abi"]>>;
}
