// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ReentrancyGuardTransient$Type } from "./ReentrancyGuardTransient";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ReentrancyGuardTransient"]: ReentrancyGuardTransient$Type;
    ["@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol:ReentrancyGuardTransient"]: ReentrancyGuardTransient$Type;
  }

  interface ContractTypesMap {
    ["ReentrancyGuardTransient"]: GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>;
    ["@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol:ReentrancyGuardTransient"]: GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>;
  }
}
