// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ReentrancyGuardTransient$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ReentrancyGuardTransient",
  "sourceName": "@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol",
  "abi": [
    {
      "inputs": [],
      "name": "ReentrancyGuardReentrantCall",
      "type": "error"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ReentrancyGuardTransient",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol:ReentrancyGuardTransient",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ReentrancyGuardTransient",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol:ReentrancyGuardTransient",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ReentrancyGuardTransient",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/ReentrancyGuardTransient.sol:ReentrancyGuardTransient",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ReentrancyGuardTransient$Type["abi"]>>;
}
